# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagesgallery', '0002_auto_20190305_0859'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
