# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagesgallery', '0003_delete_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='category',
        ),
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='imagesgallery.Category'),
            preserve_default=False,
        ),
    ]
